document.addEventListener('DOMContentLoaded',function(){const menuToggle=document.querySelector('.menu-toggle');const nav=document.querySelector('nav');if(menuToggle){menuToggle.addEventListener('click',function(){nav.classList.toggle('active');})}
const tabBtns=document.querySelectorAll('.tab-btn');tabBtns.forEach(btn=>{btn.addEventListener('click',function(){const tabGroup=this.parentElement;const allBtns=tabGroup.querySelectorAll('.tab-btn');const allContents=tabGroup.parentElement.querySelectorAll('.tab-content');allBtns.forEach(b=>b.classList.remove('active'));allContents.forEach(c=>c.classList.remove('active'));this.classList.add('active');const tabIndex=Array.from(allBtns).indexOf(this);allContents[tabIndex].classList.add('active');});});
const accordionHeaders=document.querySelectorAll('.accordion-header');accordionHeaders.forEach(header=>{header.addEventListener('click',function(){this.classList.toggle('active');const content=this.nextElementSibling;content.classList.toggle('active');});});
let currentSlide=0;const slides=document.querySelectorAll('.testimonial-slide');const dots=document.querySelectorAll('.dot');const prevBtn=document.querySelector('.carousel-btn:nth-of-type(1)');const nextBtn=document.querySelector('.carousel-btn:nth-of-type(2)');function showSlide(n){if(n>=slides.length){currentSlide=0}if(n<0){currentSlide=slides.length-1}
slides.forEach(slide=>slide.classList.remove('active'));dots.forEach(dot=>dot.classList.remove('active'));slides[currentSlide].classList.add('active');dots[currentSlide].classList.add('active');}
if(prevBtn){prevBtn.addEventListener('click',function(){currentSlide--;showSlide(currentSlide);});}
if(nextBtn){nextBtn.addEventListener('click',function(){currentSlide++;showSlide(currentSlide);});}
dots.forEach((dot,index)=>{dot.addEventListener('click',function(){currentSlide=index;showSlide(currentSlide);});});
showSlide(currentSlide);
const uploadArea=document.querySelector('.upload-area');const fileInput=document.createElement('input');fileInput.type='file';fileInput.multiple=true;fileInput.style.display='none';if(uploadArea){uploadArea.appendChild(fileInput);uploadArea.addEventListener('click',()=>fileInput.click());uploadArea.addEventListener('dragover',(e)=>{e.preventDefault();uploadArea.style.borderColor='#FFD700';});uploadArea.addEventListener('dragleave',()=>{uploadArea.style.borderColor='#002B5B';});uploadArea.addEventListener('drop',(e)=>{e.preventDefault();uploadArea.style.borderColor='#002B5B';const files=e.dataTransfer.files;handleFiles(files);});fileInput.addEventListener('change',(e)=>{handleFiles(e.target.files);});}
function handleFiles(files){const uploadedFiles=document.querySelector('.uploaded-files');if(!uploadedFiles)return;for(let file of files){const fileItem=document.createElement('div');fileItem.className='file-item success';fileItem.innerHTML=`<span>${file.name} (${(file.size/1024).toFixed(2)}KB)</span><button onclick="this.parentElement.remove()" style="background:#28a745;color:#fff;border:none;padding:5px 10px;border-radius:3px;cursor:pointer;">✓</button>`;uploadedFiles.appendChild(fileItem);}}
const form=document.querySelector('form');if(form){form.addEventListener('submit',function(e){e.preventDefault();const formData=new FormData(this);const formMessage=document.querySelector('.form-message');if(formMessage){formMessage.className='form-message success';formMessage.textContent='Thank you! We\'ll get back to you soon.';setTimeout(()=>{formMessage.classList.remove('success');form.reset();},3000);}});}